# Generated by Django 3.2.5 on 2021-10-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
