# Generated by Django 3.2.5 on 2021-10-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20211014_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.job'),
        ),
    ]
