# Generated by Django 3.2.5 on 2021-10-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20211014_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='workers', to='staff.Person'),
        ),
    ]
