# Generated by Django 3.2.5 on 2021-10-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_manager_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
