# Generated by Django 3.2.5 on 2021-10-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_person_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
